### ISSUE TITLE
Please read me.

### ISSUE THREAD

**Issue by glerinsonum** [eth0izzle/the-endorser#1]
@eth0izzle Hi. 

I have the Maltego CE Program. 
I would like to knows from you, how I can execute this python script into Maltego. 
Cordially thank you. 

![capture](https://user-images.githubusercontent.com/21057103/26980155-23d74292-4ce6-11e7-8508-52eb16566748.PNG)

**Comment by eth0izzle** [comment]
@glerinsonum Hi, The Endorser doesn't support Maltego natively and you would need to write your own transforms. I don't have any experience with this but https://sroberts.github.io/2015/03/03/maltego-transforms-for-the-lazy/ seems like a good guide.
