### ISSUE TITLE
Broken CSS selectors

### ISSUE THREAD

**Issue by mhkeller** [eth0izzle/the-endorser#3]
Hi, This script appears to no longer work. I was able to fix the login selectors by using these ids

```python
self.webdriver.find_element_by_id("username").send_keys(self.email)
self.webdriver.find_element_by_id("password").send_keys(self.password)
self.webdriver.find_element_by_css_selector(".login__form_action_container button").submit()
```

but I am stuck on this one since I'm not sure which DOM element this selector corresponds to.

```
Message: no such element: Unable to locate element: {"method":"class name","selector":"pv-top-card-section__name"}
```

Saving the user_id also appears broken but I just commented out the part where it searches for the voyager body response.

**Comment by lifeHacker42** [comment]
I'm getting this error and I'm still not sure how to fix it. Traceback is saying there's something wrong in linkedin.py line 97

**Comment by eth0izzle** [comment]
Hi @lifeHacker42 the CSS selectors had changed again - do a git pull and it should work

**Comment by haris419** [comment]
Getting a similar error:
Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="username"]"}

Do you think you can help with it?
