### ISSUE TITLE
Unable to run it

### ISSUE THREAD

**Issue by OSINT007** [eth0izzle/the-endorser#6]
Hello,

I'm trying to run it....I've install the chrome driver correctly - I think? i put it in the drivers folder of the-endorser.

When I try to run it I get this:

`python the-endorser.py https://www.linkedin.com/in/XXXX https://www.linkedin.com/in/XXX` 
Traceback (most recent call last):
  File "the-endorser.py", line 3, in <module>
    from urllib.parse import urlparse
ImportError: No module named parse

Any ideas what could be wrong?

**Comment by eth0izzle** [comment]
Use python3.

**Comment by OSINT007** [comment]
Hello,

I’ve also tried running it with python3. I get the same message.

**Comment by eth0izzle** [comment]
Can you share your `python --version`
