### ISSUE TITLE
Something wrong with login maybe

### ISSUE THREAD

**Issue by Rosanna11235813213455** [eth0izzle/the-endorser#7]
Hello,
i wrote credentials to config.yaml, not using "saved_cookie" and assigned "False" to it. And i have this: 
![image](https://user-images.githubusercontent.com/32495064/70989600-f7287200-20d4-11ea-869a-73c2e3f901a6.png)

**Comment by eth0izzle** [comment]
Thanks for the heads up @Rosanna11235813213455. It looks like LinkedIn modified their API response. If you do a `git pull` it should work for you now.
